codecov:
  require_ci_to_pass: true
  notify:
    require_base: false
    require_head: false

comment:
  require_base: false
  require_head: false

coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 1%
    patch:
      default:
        target: 70%