"""Config sub-package: global settings, constants, and scenario definitions."""

from strategify.config.scenarios import (
    DEFAULT_ACTOR_CONFIGS,
    DEFAULT_ALLIANCES,
    DEFAULT_REGION_RESOURCES,
    list_scenarios,
    load_scenario,
    scenario_to_configs,
)
from strategify.config.settings import (
    CONTAGION_WEIGHT,
    DEFAULT_N_STEPS,
    DISTANCE_DECAY_OFFSET,
    ESCALATION_LEVELS,
    ESCALATION_THRESHOLDS,
    ESCALATION_TRANSITION_COSTS,
    GEO_DIR,
    INFLUENCE_WEIGHT,
    MESA_SERVER_PORT,
    PACKAGE_ROOT,
    PERSONALITY_BIAS_BASE,
    RANDOM_SEED,
    REAL_WORLD_GEOJSON,
    REGION_COLORS,
    REGION_HEX_COLORS,
    RESOURCE_BASELINE,
    SCENARIOS_DIR,
    get_region_color,
    get_region_hex_color,
)

__all__ = [
    "PACKAGE_ROOT",
    "GEO_DIR",
    "SCENARIOS_DIR",
    "REAL_WORLD_GEOJSON",
    "DEFAULT_N_STEPS",
    "RANDOM_SEED",
    "MESA_SERVER_PORT",
    "REGION_COLORS",
    "REGION_HEX_COLORS",
    "ESCALATION_LEVELS",
    "ESCALATION_THRESHOLDS",
    "ESCALATION_TRANSITION_COSTS",
    "INFLUENCE_WEIGHT",
    "CONTAGION_WEIGHT",
    "PERSONALITY_BIAS_BASE",
    "RESOURCE_BASELINE",
    "DISTANCE_DECAY_OFFSET",
    "get_region_color",
    "get_region_hex_color",
    "DEFAULT_ACTOR_CONFIGS",
    "DEFAULT_REGION_RESOURCES",
    "DEFAULT_ALLIANCES",
    "list_scenarios",
    "load_scenario",
    "scenario_to_configs",
]
