"""Autonomous LLM Agent Swarm Orchestrator.

Orchestrates specialized LLM agent personas (Defense Minister, Chief Epidemiologist,
Finance Minister, Diplomatic Envoy) to deliberate, negotiate, and synthesize
strategic action vectors within MultiDomainWargameEngine simulations.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from strategify.sim.wargame import DomainStateSnapshot, MultiDomainWargameEngine

logger = logging.getLogger(__name__)


@dataclass
class AgentProposal:
    """Proposal generated by a specialized swarm persona."""

    persona_name: str
    domain: str
    recommended_action: str
    confidence_score: float
    reasoning_chain: str


@dataclass
class SwarmDeliberationResult:
    """Outcome of a multi-agent swarm deliberation round."""

    step: int
    actor_id: str
    proposals: list[AgentProposal]
    consensus_action_vector: dict[str, Any]
    consensus_score: float


class SwarmAgentPersona:
    """Specialized LLM agent persona representing a domain minister."""

    def __init__(self, name: str, domain: str, priority_weight: float = 1.0) -> None:
        self.name = name
        self.domain = domain
        self.priority_weight = priority_weight

    def deliberate(self, snapshot: DomainStateSnapshot, actor_id: str) -> AgentProposal:
        """Formulate domain action proposal based on current state snapshot.

        Parameters
        ----------
        snapshot : DomainStateSnapshot
            Current multi-domain state.
        actor_id : str
            Actor identifier.

        Returns
        -------
        AgentProposal
            Persona proposal.
        """
        if self.domain == "Defense":
            readiness = snapshot.military_readiness.get(actor_id, 100.0)
            action = "Allocate Spectrum Bandwidth" if readiness > 50.0 else "Defensive EW Jamming"
            chain = f"Readiness is {readiness:.1f}%. Recommend {action} to secure tactical superiority."
            confidence = 0.85
        elif self.domain == "Epidemiology":
            infections = snapshot.epidemic_infections.get(actor_id, 0.0)
            action = "Implement Targeted NPI Lockdowns" if infections > 50.0 else "Expand Vaccine R&D"
            chain = f"Infection cases count is {infections:.1f}. Recommend {action} to curb transmission."
            confidence = 0.90
        elif self.domain == "Finance":
            growth = snapshot.gdp_growth_rate.get(actor_id, 0.02)
            action = "Impose Targeted Trade Tariffs" if growth >= 0.02 else "Stimulate Emergency Production"
            chain = f"Quarterly GDP growth is {growth:.2%}. Recommend {action} to preserve economic baseline."
            confidence = 0.80
        else:  # Diplomacy
            tension = snapshot.diplomatic_tensions
            action = "Propose Land-for-Peace Settlement" if tension > 0.5 else "Ratify Non-Aggression Pact"
            chain = f"Diplomatic tension metric is {tension:.2f}. Recommend {action} to reduce bilateral risk."
            confidence = 0.88

        return AgentProposal(
            persona_name=self.name,
            domain=self.domain,
            recommended_action=action,
            confidence_score=confidence,
            reasoning_chain=chain,
        )


class StrategifySwarm:
    """Orchestrator coordinating multi-agent LLM swarm deliberation rounds."""

    def __init__(self, actor_id: str = "BlueLand") -> None:
        self.actor_id = actor_id
        self.personas = [
            SwarmAgentPersona("General Vance", "Defense", priority_weight=1.2),
            SwarmAgentPersona("Dr. Aris", "Epidemiology", priority_weight=1.1),
            SwarmAgentPersona("Minister Sterling", "Finance", priority_weight=1.0),
            SwarmAgentPersona("Ambassador Chen", "Diplomacy", priority_weight=1.0),
        ]

    def deliberate_step(self, wargame_engine: MultiDomainWargameEngine) -> SwarmDeliberationResult:
        """Run a swarm deliberation round across all personas.

        Parameters
        ----------
        wargame_engine : MultiDomainWargameEngine
            Active wargame engine.

        Returns
        -------
        SwarmDeliberationResult
            Swarm deliberation outcome.
        """
        snapshot = wargame_engine.step()
        proposals = []

        total_confidence = 0.0
        weighted_score_sum = 0.0

        consensus_vector = {}

        for persona in self.personas:
            proposal = persona.deliberate(snapshot, self.actor_id)
            proposals.append(proposal)

            total_confidence += proposal.confidence_score * persona.priority_weight
            weighted_score_sum += persona.priority_weight
            consensus_vector[persona.domain] = proposal.recommended_action

        consensus_score = float(total_confidence / max(1e-4, weighted_score_sum))

        logger.info(
            "StrategifySwarm Step %d Deliberations Complete (Consensus Score: %.2f)",
            snapshot.step,
            consensus_score,
        )

        return SwarmDeliberationResult(
            step=snapshot.step,
            actor_id=self.actor_id,
            proposals=proposals,
            consensus_action_vector=consensus_vector,
            consensus_score=consensus_score,
        )
